title: Çağrı Sarıyıldız
author: Çağrı Sarıyıldız
baseurl: ""
url: "https://csariyildiz.github.io"

# TOC / Kramdown
kramdown:
  input: GFM
  toc_levels: "2,3,4"

# Pagination & permalink
paginate: 5
permalink: /:year-:month-:day-:title/

# Defaults for posts and pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc
